# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/pawel/Desktop/binary_land/uec2_projekt/src/constrs_1/imports/Basys3_Master.xdc

# IP: C:/Users/pawel/Desktop/binary_land/uec2_projekt/src/sources_1/ip/clk_generator/clk_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_generator || ORIG_REF_NAME==clk_generator} -quiet] -quiet

# XDC: c:/Users/pawel/Desktop/binary_land/uec2_projekt/src/sources_1/ip/clk_generator/clk_generator_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_generator || ORIG_REF_NAME==clk_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/pawel/Desktop/binary_land/uec2_projekt/src/sources_1/ip/clk_generator/clk_generator.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_generator || ORIG_REF_NAME==clk_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/pawel/Desktop/binary_land/uec2_projekt/src/sources_1/ip/clk_generator/clk_generator_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_generator || ORIG_REF_NAME==clk_generator} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/pawel/Desktop/binary_land/uec2_projekt/src/sources_1/ip/clk_generator/clk_generator_ooc.xdc
